<a href="https://colab.research.google.com/github/Sudorenkoroma/HW_GI_ML/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

Створення одновимірного масиву з першими 10-ма натуральними числами

In [4]:
vector = np.arange(1, 11)
vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Створення двовимірного масиву 3x3, заповненого нулями

In [5]:
matrix_zeros = np.zeros((3, 3))
matrix_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Створення масиву 5x5 з випадковими цілими числами від 1 до 10

In [6]:
matrix_random_int = np.random.randint(1, 11, size=(5, 5))
matrix_random_int

array([[10,  4, 10,  8,  2],
       [10,  7,  8,  6,  7],
       [ 6, 10,  1,  2,  1],
       [ 6,  7,  4,  5,  4],
       [ 9,  9,  2,  7,  4]])

Створення масиву 4x4 з випадковими дійсними числами від 0 до

In [7]:
matrix_random_float = np.random.rand(4, 4)
matrix_random_float

array([[0.68576208, 0.18934854, 0.10131329, 0.43858269],
       [0.35561092, 0.12255825, 0.56854406, 0.80869259],
       [0.0381474 , 0.80592867, 0.30161209, 0.03241212],
       [0.52249243, 0.59166776, 0.24705312, 0.28944985]])

Створення двох одновимірних масивів розміром 5 з випадковими цілими числами від 1 до 10

In [17]:
vector1 = np.random.randint(1, 11, size=5)
vector2 = np.random.randint(1, 11, size=5)
vector1 + vector2, vector1 - vector2, vector1 * vector2,

(array([14, 10, 13, 10, 15]),
 array([ 4,  6, -7, -4,  3]),
 array([45, 16, 30, 21, 54]))

Створення двох векторів розміром 7 і знаходження їх скалярного добутку

In [12]:
vector3 = np.random.rand(7)
vector4 = np.random.rand(7)
dot_product = np.dot(vector3, vector4)
dot_product

1.7398699446051695

Створення і перемноження двох матриць розміром 2x2 та 2x3

In [13]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))
matrix_product = np.dot(matrix1, matrix2)
matrix_product

array([[15, 11, 34],
       [16, 12, 36]])

Обернена матриця для матриці 3x3

In [18]:
matrix3 = np.random.randint(1, 11, size=(3, 3))
inverse_matrix = np.linalg.inv(matrix3)
matrix3, inverse_matrix

(array([[ 3, 10,  6],
        [ 3,  3,  9],
        [ 8,  2,  8]]),
 array([[ 0.01538462, -0.17435897,  0.18461538],
        [ 0.12307692, -0.06153846, -0.02307692],
        [-0.04615385,  0.18974359, -0.05384615]]))

Транспонування матриці 4x4

In [19]:
matrix4 = np.random.rand(4, 4)
transposed_matrix = matrix4.T
matrix4, transposed_matrix

(array([[0.89865608, 0.48088816, 0.27728523, 0.76044591],
        [0.52756006, 0.1264314 , 0.23107215, 0.0606903 ],
        [0.59280828, 0.38099833, 0.27427093, 0.52708188],
        [0.92056027, 0.4449648 , 0.71171314, 0.3130463 ]]),
 array([[0.89865608, 0.52756006, 0.59280828, 0.92056027],
        [0.48088816, 0.1264314 , 0.38099833, 0.4449648 ],
        [0.27728523, 0.23107215, 0.27427093, 0.71171314],
        [0.76044591, 0.0606903 , 0.52708188, 0.3130463 ]]))

Перемноження матриці 3x4 на вектор розміром 4

In [21]:
matrix5 = np.random.randint(1, 11, size=(3, 4))
vector5 = np.random.randint(1, 11, size=4)
matrix_vector_product = np.dot(matrix5, vector5)
matrix_vector_product

array([ 51,  74, 107])

Перемноження матриці 2x3 на вектор розміром 3 з випадковими дійсними числами

In [22]:
matrix6 = np.random.rand(2, 3)
vector6 = np.random.rand(3)
result1 = np.dot(matrix6, vector6)
result1

array([1.56064033, 0.73241169])

Поелементне множення двох матриць 2x2

In [23]:
matrix7 = np.random.randint(1, 11, size=(2, 2))
matrix8 = np.random.randint(1, 11, size=(2, 2))
elementwise_product = np.multiply(matrix7, matrix8)
elementwise_product

array([[24, 35],
       [28, 18]])

Добуток двох матриць 2x2

In [25]:
matrix9 = np.random.randint(1, 11, size=(2, 2))
matrix10 = np.random.randint(1, 11, size=(2, 2))
product_matrix = np.dot(matrix9, matrix10)
product_matrix

array([[44, 46],
       [49, 40]])

Сума елементів матриці 5x5

In [26]:
matrix_for_sum = np.random.randint(1, 101, size=(5, 5))
sum_elements = np.sum(matrix9)
sum_elements

17

Різниця між двома матрицями 4x4

In [27]:
matrix10 = np.random.randint(1, 11, size=(4, 4))
matrix11 = np.random.randint(1, 11, size=(4, 4))
difference_matrix = np.subtract(matrix10, matrix11)
difference_matrix

array([[-6, -5,  4,  1],
       [ 0, -8,  0,  1],
       [ 3, -1,  2,  3],
       [-2, -1, -4,  5]])

Сума елементів кожного рядка матриці 3x3

In [28]:
matrix12 = np.random.rand(3, 3)
row_sums = np.sum(matrix12, axis=1)
row_sums

array([1.49511427, 1.36732813, 1.79246148])

Квадрати елементів матриці 3x4

In [29]:
matrix13 = np.random.randint(1, 11, size=(3, 4))
squared_matrix = np.square(matrix13)
squared_matrix

array([[ 64,  81,  16, 100],
       [ 49,  49,  25,  25],
       [  9,   9,  25, 100]])

Вектор з квадратними коренями чисел

In [30]:
vector7 = np.random.randint(1, 51, size=4)
sqrt_vector = np.sqrt(vector7)
sqrt_vector

array([4.47213595, 4.12310563, 4.        , 4.        ])